### PR TITLE
chore: enforce restricted PSS

### PR DESCRIPTION
**Pull request by SdgJlbl**
fixes fl-1610

### CODE REVIEW

**Review by thbcmlowk — APPROVED** [review]
Thanks👮‍♀️! Should we run `/e2e`?

**Comment by SdgJlbl** [comment]
> Thanks👮‍♀️! Should we run `/e2e`?

We can
I would also like to try out the chart on dev before merging

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]
Thanks!

**Pull request merged**
