### PR TITLE
chore: bump axio and bable with npm audit

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Notes for developers and reviewers:

-   Think to update CHANGELOG.md before merge if needed !

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]
LGTM

**Pull request merged**
