### PR TITLE
feat: e2e general tests

### PR DESCRIPTION
**Pull request by Milouu**
## Description

Add menu tests to e2e testing, which correspond to 'general tests' of our testing plan

Fixes FL-1076

### CODE REVIEW

**Comment by oleobal** [comment]
\e2e --tests frontend

I think this should run your new tests

**Comment by oleobal** [comment]
/e2e --tests frontend

I think this should run your new tests

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by oleobal** [comment]
[The image building fails](https://console.cloud.google.com/cloud-build/builds;region=us-east1/57dc0777-b334-4139-b6e3-14f89b921792?project=connect-314908) due to this error: `Step #2: error building image: error building stage: failed to optimize instructions: failed to get files used from context: failed to get fileinfo for /workspace/substra-frontend/e2e-tests/cypress.json: lstat /workspace/substra-frontend/e2e-tests/cypress.json: no such file or directory`

Because we forgot to update the dockerfile to match #219 

I think we only need edit this line: https://github.com/Substra/substra-frontend/blob/main/docker/substra-frontend-tests/Dockerfile#L5

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
