### PR TITLE
fix(deps): revert `@chakra-ui/react` to 2.6.1

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Notes for developers and reviewers:

-   Think to update CHANGELOG.md before merge if needed !

### CODE REVIEW

**Review by ThibaultFy — APPROVED** [review]
thx

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
Thanks!

**Pull request merged**
