### PR TITLE
Feat/e2e tests rebased

### PR DESCRIPTION
**Pull request by thbcmlowk**
## Notes for developers and reviewers:

-   Think to update CHANGELOG.md before merge if needed !

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by thbcmlowk** [comment]
/e2e --tests=sdk,substrafl,mnist,frontend --refs=substra-ci=refactor/frontend-tests-on-all-tests

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request closed without merging**
